name: admin_portal_e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  collection: ^1.19.1
  dotted_border: ^2.1.0
  multi_select_flutter: ^4.1.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/lang