// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0XjiPRS98wQjb53PVpAJil1SyQVGvvo',
    appId: '1:511275680482:web:57308a29396558a6ee54bb',
    messagingSenderId: '511275680482',
    projectId: 'e-commerce-test-be97f',
    authDomain: 'e-commerce-test-be97f.firebaseapp.com',
    storageBucket: 'e-commerce-test-be97f.firebasestorage.app',
    measurementId: 'G-TJE7Q59BF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGVXXexHvyIbeYrSOCNZsyGQTlKhpuxlk',
    appId: '1:511275680482:android:97e0fe6e0dfe1123ee54bb',
    messagingSenderId: '511275680482',
    projectId: 'e-commerce-test-be97f',
    storageBucket: 'e-commerce-test-be97f.firebasestorage.app',
  );
}
